### ISSUE TITLE
tfsec `v0.40.01` ignore rules inconsistent - raises error code on `AWS093` and `AWS032`

### ISSUE THREAD

**Issue by johannesgiorgis-galvanize** [tfsec/tfsec#781]
**Describe the bug**
Our CI builds started failing yesterday with the release of tfsec v0.40.0. Where v0.39.42 ran fine previously, the recently released v0.40.0 and v0.40.1 are causing us issues. Specifically, we were ignoring `AWS093` and `AWS032` but started seeing their respective error messages pop up when running tfsec in our CI builds, which leads to failures. I installed the latest version via brew (`v0.40.1`) and verified locally the same error is occurring. 

Further testing indicates that the rules are successfully ignored when passed through the command line using the `-e` flag but if they are added into the terraform file via `#tfsec:ignore:AWS093`, they aren't being ignored.

**To Reproduce**
1. Install tfsec `v0.40.01` or up
2. Run `tfsec` against a terraform file which contains `#tfsec:ignore:AWS093` -> see an error
3. Try running `tfsec -e AWS093` against that same file -> see no error as expected

**Expected behavior**
tfsec should ignore the rules as defined using the `#tfsec:ignore:XXXXXX` format

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux docker images, Mac OS

**Additional context**

Below is a snippet of the output with our code removed:

```sh
Check 1

  [AWS093][INFO] Resource 'aws_ecr_repository.bert' does not have CMK encryption configured
  /Users/johannes.giorgis/src/professional/ernie/services/bert/main.tf:27-35


<...relevant code snippet skipped...>

  Impact:     Using AWS managed keys does not allow for fine grained control
  Resolution: Use customer managed keys


Check 2

  [AWS093][INFO] Resource 'aws_ecr_repository.bert' should have the encryption type set to KMS
  :0
```

**Comment by owenrumney** [comment]
Hey @johannesgiorgis-galvanize  - I see the issue, its resolved in #782

**Comment by owenrumney** [comment]
@johannesgiorgis-galvanize - this is resolved in v0.40.2

**Comment by budougumi0617** [comment]
@owenrumney I appreciate your quick fix. however, I think that this issue is not resolved on v0.40.2 yet.

The reproduce steps are below.


```hcl
$ cat sample.tf
resource "aws_ecr_repository" "tfsec_sample" {
  #tfsec:ignore:AWS078
  #tfsec:ignore:AWS093
  name = "tfsec-sample"

  image_scanning_configuration {
    scan_on_push = true
  }
}
```

v0.39.42 ignores AWS093.

```
$ docker run --rm -it -v "$(pwd):/src" tfsec/tfsec:v0.39.42 /src

  times
  ------------------------------------------
  disk i/o             6.9766ms
  parsing HCL          11.5µs
  evaluating values    54.1µs
  running checks       2.5756ms

  counts
  ------------------------------------------
  files loaded         1
  blocks               1
  evaluated blocks     1
  modules              0
  module blocks        0
  ignored checks       2

No problems detected!

```

but, v0.40.2 does not ignore AWS093.

```bash
$ docker run --rm -it -v "$(pwd):/src" tfsec/tfsec:v0.40.2 /src

Check 1

  [AWS093][INFO] Resource 'aws_ecr_repository.tfsec_sample' should have the encryption type set to KMS
  :0


  Impact:     Using AWS managed keys does not allow for fine grained control
  Resolution: Use customer managed keys


  times
  ------------------------------------------
  disk i/o             7.0384ms
  parsing HCL          15.9µs
  evaluating values    66µs
  running checks       5.9425ms

  counts
  ------------------------------------------
  files loaded         1
  blocks               1
  evaluated blocks     1
  modules              0
  module blocks        0
  ignored checks       2

1 potential problems detected.
```

**Comment by owenrumney** [comment]
Hi @budougumi0617 - I believe the ignore should be above the offending line or if it is an absence that’s being ignored it should be on the line above the block

**Comment by budougumi0617** [comment]
Thank you your quick response, Our codes were wrong. I can ignore warning by put ignore comment above the block. Thx!!!

```hcl
#tfsec:ignore:AWS093
resource "aws_ecr_repository" "tfsec_sample" {
  #tfsec:ignore:AWS078
  name = "tfsec-sample"

  image_scanning_configuration {
    scan_on_push = true
  }
}
```

**Comment by johannesgiorgis-galvanize** [comment]
Thanks @owenrumney ! So was this bug a result of a more strict checks in v0.40.0 and up? As you can explain in your previous comment? Cheers!

> Hi @budougumi0617 - I believe the ignore should be above the offending line or if it is an absence that’s being ignored it should be on the line above the block

**Comment by owenrumney** [comment]
Hi @johannesgiorgis-galvanize it was introduced in 0.40 when we did a large refactor and trimmed down the result object. When we did that, we introduced a bug where the range object didn’t always have a Filename attribute populated; this would occur when the issue identified was on a sub range of the overall resource block.

the fix this morning ensures that the resource block range is always used to in the ignore check code so this would not happen again

**Comment by johannesgiorgis-galvanize** [comment]
> Hi @johannesgiorgis-galvanize it was introduced in 0.40 when we did a large refactor and trimmed down the result object. When we did that, we introduced a bug where the range object didn’t always have a Filename attribute populated; this would occur when the issue identified was on a sub range of the overall resource block.
> 
> the fix this morning ensures that the resource block range is always used to in the ignore check code so this would not happen again

Thanks for the explanation and for the prompt responses/fixes as always! Keep up the great work 👍 😄
